In [69]:
import pandas as pd
import numpy as np
from sklearn import metrics
df = pd.read_csv("adult.csv")
df

39          State-gov   77516    Bachelors   13        Never-married  \
0      50   Self-emp-not-inc   83311    Bachelors   13   Married-civ-spouse   
1      38            Private  215646      HS-grad    9             Divorced   
2      53            Private  234721         11th    7   Married-civ-spouse   
3      28            Private  338409    Bachelors   13   Married-civ-spouse   
4      37            Private  284582      Masters   14   Married-civ-spouse   
...    ..                ...     ...          ...  ...                  ...   
32555  27            Private  257302   Assoc-acdm   12   Married-civ-spouse   
32556  40            Private  154374      HS-grad    9   Married-civ-spouse   
32557  58            Private  151910      HS-grad    9              Widowed   
32558  22            Private  201490      HS-grad    9        Never-married   
32559  52       Self-emp-inc  287927      HS-grad    9   Married-civ-spouse   

             Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0         Exec-managerial         Husband   White     Male      0   0   13   
1       Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2       Handlers-cleaners         Husband   Black     Male      0   0   40   
3          Prof-specialty            Wife   Black   Female      0   0   40   
4         Exec-managerial            Wife   White   Female      0   0   40   
...                   ...             ...     ...      ...    ...  ..  ...   
32555        Tech-support            Wife   White   Female      0   0   38   
32556   Machine-op-inspct         Husband   White     Male      0   0   40   
32557        Adm-clerical       Unmarried   White   Female      0   0   40   
32558        Adm-clerical       Own-child   White     Male      0   0   20   
32559     Exec-managerial            Wife   White   Female  15024   0   40   

        United-States   <=50K  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3                Cuba   <=50K  
4       United-States   <=50K  
...               ...     ...  
32555   United-States   <=50K  
32556   United-States    >50K  
32557   United-States   <=50K  
32558   United-States   <=50K  
32559   United-States    >50K  

[32560 rows x 15 columns]

In [70]:
df.columns = ['Age', 'Workclass', 'Fnlwgt', 'Education', 'education_num', 'marital_status', 
              'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 
              'hours_per_week', 'native_country', 'income']
df

Age          Workclass  Fnlwgt    Education  education_num  \
0       50   Self-emp-not-inc   83311    Bachelors             13   
1       38            Private  215646      HS-grad              9   
2       53            Private  234721         11th              7   
3       28            Private  338409    Bachelors             13   
4       37            Private  284582      Masters             14   
...    ...                ...     ...          ...            ...   
32555   27            Private  257302   Assoc-acdm             12   
32556   40            Private  154374      HS-grad              9   
32557   58            Private  151910      HS-grad              9   
32558   22            Private  201490      HS-grad              9   
32559   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0       Married-civ-spouse     Exec-managerial         Husband   White   
1                 Divorced   Handlers-cleaners   Not-in-family   White   
2       Married-civ-spouse   Handlers-cleaners         Husband   Black   
3       Married-civ-spouse      Prof-specialty            Wife   Black   
4       Married-civ-spouse     Exec-managerial            Wife   White   
...                    ...                 ...             ...     ...   
32555   Married-civ-spouse        Tech-support            Wife   White   
32556   Married-civ-spouse   Machine-op-inspct         Husband   White   
32557              Widowed        Adm-clerical       Unmarried   White   
32558        Never-married        Adm-clerical       Own-child   White   
32559   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male             0             0              13   United-States   
1         Male             0             0              40   United-States   
2         Male             0             0              40   United-States   
3       Female             0             0              40            Cuba   
4       Female             0             0              40   United-States   
...        ...           ...           ...             ...             ...   
32555   Female             0             0              38   United-States   
32556     Male             0             0              40   United-States   
32557   Female             0             0              40   United-States   
32558     Male             0             0              20   United-States   
32559   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32555   <=50K  
32556    >50K  
32557   <=50K  
32558   <=50K  
32559    >50K  

[32560 rows x 15 columns]

In [71]:
# dropping columns with noisy data
df.drop(['education_num','Age','hours_per_week','Fnlwgt','capital_gain','capital_loss','native_country'], axis=1, inplace=True)

# Data Cleaning

In [72]:
#running a loop of value_counts of each column to find out unique values. 
for c in df.columns:
    print ("---- %s ---" % c)
    print (df[c].value_counts())

---- Workclass ---
 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: Workclass, dtype: int64
---- Education ---
 HS-grad         10501
 Some-college     7291
 Bachelors        5354
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: Education, dtype: int64
---- marital_status ---
 Married-civ-spouse       14976
 Never-married            10682
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: marital_status, dtype: int64
---- occ

In [73]:
df.isin(['?']).sum(axis=0)


Workclass         0
Education         0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
income            0
dtype: int64

In [74]:
df['Workclass'] = df['Workclass'].replace('?',np.nan)
df['occupation'] = df['occupation'].replace('?',np.nan)
#dropping the NaN rows now 
df.dropna(how='any',inplace=True)

# Converting all values in integers

In [75]:
from sklearn.preprocessing import LabelEncoder

In [76]:
df = df.apply(LabelEncoder().fit_transform)
df.head()

Workclass  Education  marital_status  occupation  relationship  race  sex  \
0          6          9               2           4             0     4    1   
1          4         11               0           6             1     4    1   
2          4          1               2           6             0     2    1   
3          4          9               2          10             5     2    0   
4          4         12               2           4             5     4    0   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

In [77]:
df.isnull().sum()   # checking NULL values

Workclass         0
Education         0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
income            0
dtype: int64

In [78]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)

(32560, 7)
(32560,)


## Removing Duplicate Values

In [79]:
df.drop_duplicates(keep=False,inplace=True)
df.duplicated().sum()

0

# Spliting testing and training data

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)        # 80:20 ratio
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(26048, 7)
(6512, 7)
(26048,)
(6512,)


# Classifier Models

# 1. Applying Decision Tree Classifier

In [82]:
from sklearn.tree import DecisionTreeClassifier

In [83]:
m1 = DecisionTreeClassifier(criterion='gini',max_depth=9)
m1.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=9)

In [84]:
# R2_score
print("Training Score",m1.score(x_train,y_train))
print("Testing Score",m1.score(x_test,y_test))

Training Score 0.8353040540540541
Testing Score 0.8272420147420148


### Confusion matrix and Classification report

In [85]:
from sklearn.metrics import confusion_matrix,classification_report

In [110]:
ypred_m1 = m1.predict(x_test)                                    #for prediction of income of test data
print("Prediction of income of test data : ",ypred_m1)

Prediction of income of test data :  [0 0 0 ... 0 0 0]


In [87]:
cm_m1 = confusion_matrix(y_test,ypred_m1)
print(cm_m1)
print(classification_report(y_test,ypred_m1))

[[4595  408]
 [ 717  792]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.89      5003
           1       0.66      0.52      0.58      1509

    accuracy                           0.83      6512
   macro avg       0.76      0.72      0.74      6512
weighted avg       0.82      0.83      0.82      6512



### Finding percentage of misclassification & validating Precision, Recall, F1_score, Accuracy

Let confusion matrix be in form 
| a b |
| c d |

Then prececision and Recall are 
 pre0 = a/(a+c)  rec0 = a/(a+b) 
 pre1 = d/(b+d)  rec1 = d/(c+d)
 
F1_score are
    f1s0 = 2*pre0*rec0/(pre0+rec0)  f1s1 = 2*pre1*rec1/(pre1+rec1)

accuracy = (a+d)/(a+b+c+d)

% of misclassification = (b+c)/(a+b+c+d)  *100

In [117]:
a,b,c,d = 4595,408,717,792
pre0 = a/(a+c)
pre1 = d/(b+d)
rec0 = a/(a+b)
rec1 = d/(c+d)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.8650225903614458
Pre1 0.66
Rec0 0.918448930641615
Rec1 0.5248508946322068


In [118]:
f1s0 = (2*pre0*rec0)/(pre0+rec0)
f1s1 = (2*pre1*rec1)/(pre1+rec1)
acc = (a+d)/(a+b+c+d)
print('F1_score are',f1s0,f1s1)
print('Accuracy : ',acc)

F1_score are 0.8909355307804169 0.5847176079734219
Accuracy :  0.8272420147420148


In [119]:
mis = ((b+c)*100)/(a+b+c+d)
print('Percentage of misclassification is ',mis)

Percentage of misclassification is  17.275798525798525


# 2. Applying Random Forest Classifier

In [88]:
from sklearn.ensemble import RandomForestClassifier

In [89]:
m2 = RandomForestClassifier(n_estimators=45, criterion='entropy',max_depth=8,min_samples_split=12) 
m2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=8, min_samples_split=12,
                       n_estimators=45)

In [90]:
# R2_score
print("Training Score",m2.score(x_train,y_train))
print("Testing Score",m2.score(x_test,y_test))

Training Score 0.8307739557739557
Testing Score 0.8339987714987716


### Confusion matrix and Classification report

In [137]:
ypred_m2 = m2.predict(x_test)                   #for prediction of income of test data
print("Prediction of income of test data : ",ypred_m1)

Prediction of income of test data :  [0 0 0 ... 0 0 0]


In [92]:
cm_m2 = confusion_matrix(y_test,ypred_m2)
print(cm_m2)
print(classification_report(y_test,ypred_m2,zero_division=0))

[[4612  391]
 [ 690  819]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.90      5003
           1       0.68      0.54      0.60      1509

    accuracy                           0.83      6512
   macro avg       0.77      0.73      0.75      6512
weighted avg       0.83      0.83      0.83      6512



### Finding percentage of misclassification & validating Precision, Recall, F1_score, Accuracy

In [120]:
a,b,c,d = 4612,391,690,819
pre0 = a/(a+c)
pre1 = d/(b+d)
rec0 = a/(a+b)
rec1 = d/(c+d)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.8698604300264051
Pre1 0.6768595041322314
Rec0 0.9218468918648811
Rec1 0.5427435387673957


In [121]:
f1s0 = (2*pre0*rec0)/(pre0+rec0)
f1s1 = (2*pre1*rec1)/(pre1+rec1)
acc = (a+d)/(a+b+c+d)
print('F1_score are',f1s0,f1s1)
print('Accuracy : ',acc)

F1_score are 0.8950994662785057 0.6024273630011033
Accuracy :  0.8339987714987716


In [122]:
mis = ((b+c)*100)/(a+b+c+d)
print('Percentage of misclassification is ',mis)

Percentage of misclassification is  16.60012285012285


# 3. Applying LogisticRegression Classifier

In [93]:
from sklearn.linear_model import LogisticRegression

In [94]:
m3 = LogisticRegression(solver='liblinear')
m3.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [95]:
# R2_score
print("Training Score",m3.score(x_train,y_train))
print("Testing Score",m3.score(x_test,y_test))

Training Score 0.7507294226044227
Testing Score 0.7610565110565111


### Confusion matrix and Classification report

In [138]:
ypred_m3 = m3.predict(x_test)                                #for prediction of income of test data
print("Prediction of income of test data : ",ypred_m1)

Prediction of income of test data :  [0 0 0 ... 0 0 0]


In [97]:
cm_m3 = confusion_matrix(y_test,ypred_m3)
print(cm_m3)
print(classification_report(y_test,ypred_m3,zero_division=0))

[[4949   54]
 [1502    7]]
              precision    recall  f1-score   support

           0       0.77      0.99      0.86      5003
           1       0.11      0.00      0.01      1509

    accuracy                           0.76      6512
   macro avg       0.44      0.50      0.44      6512
weighted avg       0.62      0.76      0.67      6512



### Finding percentage of misclassification & validating Precision, Recall, F1_score, Accuracy

In [123]:
a,b,c,d = 4949,54,1502,7
pre0 = a/(a+c)
pre1 = d/(b+d)
rec0 = a/(a+b)
rec1 = d/(c+d)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.7671678809486902
Pre1 0.11475409836065574
Rec0 0.9892064761143314
Rec1 0.004638833664678595


In [125]:
f1s0 = (2*pre0*rec0)/(pre0+rec0)
f1s1 = (2*pre1*rec1)/(pre1+rec1)
acc = (a+d)/(a+b+c+d)
print('F1_score are',f1s0,f1s1)
print('Accuracy : ',acc)

F1_score are 0.8641522612187882 0.0089171974522293
Accuracy :  0.7610565110565111


In [126]:
mis = ((b+c)*100)/(a+b+c+d)
print('Percentage of misclassification is ',mis)

Percentage of misclassification is  23.894348894348894


# 4. Applying KNN Classifier

In [98]:
from sklearn.neighbors import KNeighborsClassifier

In [99]:
m4 = KNeighborsClassifier(n_neighbors=91)
m4.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=91)

In [100]:
# R2_score
print("Training Score",m4.score(x_train,y_train))
print("Testing Score",m4.score(x_test,y_test))

Training Score 0.8234413390663391
Testing Score 0.82754914004914


### Confusion matrix and Classification report

In [139]:
ypred_m4 = m4.predict(x_test)                         #for prediction of income of test data
print("Prediction of income of test data : ",ypred_m1)

Prediction of income of test data :  [0 0 0 ... 0 0 0]


In [102]:
cm_m4 = confusion_matrix(y_test,ypred_m4)
print(cm_m4)
print(classification_report(y_test,ypred_m4,zero_division=0))

[[4648  355]
 [ 768  741]]
              precision    recall  f1-score   support

           0       0.86      0.93      0.89      5003
           1       0.68      0.49      0.57      1509

    accuracy                           0.83      6512
   macro avg       0.77      0.71      0.73      6512
weighted avg       0.82      0.83      0.82      6512



### Finding percentage of misclassification & validating Precision, Recall, F1_score, Accuracy

In [127]:
a,b,c,d = 4648,355,768,741
pre0 = a/(a+c)
pre1 = d/(b+d)
rec0 = a/(a+b)
rec1 = d/(c+d)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.8581979320531757
Pre1 0.676094890510949
Rec0 0.9290425744553268
Rec1 0.49105367793240556


In [128]:
f1s0 = (2*pre0*rec0)/(pre0+rec0)
f1s1 = (2*pre1*rec1)/(pre1+rec1)
acc = (a+d)/(a+b+c+d)
print('F1_score are',f1s0,f1s1)
print('Accuracy : ',acc)

F1_score are 0.8922161435838373 0.5689059500959693
Accuracy :  0.82754914004914


In [129]:
mis = ((b+c)*100)/(a+b+c+d)
print('Percentage of misclassification is ',mis)

Percentage of misclassification is  17.245085995085994


# 5. Applying SVM Classifier

In [103]:
from sklearn.svm import SVC

In [104]:
m5 = SVC(kernel='linear',C=1)
m5.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [105]:
# R2_score
print("Training Score",m5.score(x_train,y_train))
print("Testing Score",m5.score(x_test,y_test))

Training Score 0.7569103194103194
Testing Score 0.7682739557739557


### Confusion matrix and Classification report

In [140]:
ypred_m5 = m5.predict(x_test)                          #for prediction of income of test data
print("Prediction of income of test data : ",ypred_m1)

Prediction of income of test data :  [0 0 0 ... 0 0 0]


In [107]:
cm_m5 = confusion_matrix(y_test,ypred_m5)
print(cm_m5)
print(classification_report(y_test,ypred_m5,zero_division=0))

[[5003    0]
 [1509    0]]
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      5003
           1       0.00      0.00      0.00      1509

    accuracy                           0.77      6512
   macro avg       0.38      0.50      0.43      6512
weighted avg       0.59      0.77      0.67      6512



### Finding percentage of misclassification & validating Precision, Recall, F1_score, Accuracy

In [131]:
a,b,c,d = 5003,0,1509,0
pre0 = a/(a+c)
pre1 = 0                  # divided by 0
rec0 = a/(a+b)
rec1 = 0                  # divided by 0
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.7682739557739557
Pre1 0
Rec0 1.0
Rec1 0


In [135]:
f1s0 = (2*pre0*rec0)/(pre0+rec0)
f1s1 = 0                              # divided by 0
acc = (a+d)/(a+b+c+d)
print('F1_score are',f1s0,f1s1)
print('Accuracy : ',acc)

F1_score are 0.8689535388623534 0
Accuracy :  0.7682739557739557


In [136]:
mis = ((b+c)*100)/(a+b+c+d)
print('Percentage of misclassification is ',mis)

Percentage of misclassification is  23.172604422604422
